# -*- coding: utf-8 -*-
"""numpy18.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Rp05a1L7Q73qzaI8BrAnI5qmXXVXGfOq
"""

pip install numpy

import numpy as np
print(np.__version__)

import numpy as np
arr = np.zeros((5,5))
print(arr)

import numpy as np
arr = np.ones((5,7))
print(arr)

import numpy as np
arr = np.full((4,7),9)
print(arr)

import numpy as np
arr = np.empty((5,5))
print(arr)

import numpy as np
arr = np.eye(5)
print(arr)

import numpy as np
arr = np.arange(1,101,2)
print(arr)

import numpy as np
Even= np.arange(2,200,2)
print(arr)

import numpy as np
arr = np.linspace(1,20,7)
print(arr)

import numpy as np
arr=np.random.rand(10)
print(arr)

import numpy as np
arr = np.random.randint(100)
print(arr)

import numpy as np
colours = ["red","green","pink","orange","blue","white","black"]
print(np.random.choice(colours,2))

import numpy as np
arr = np.array([1,2,3])
new = arr.copy()
new[1] = 100
print("Array value is :",arr)
print("copy value is :",new)

import numpy as np
arr=np.array([5,10,15,20,25,30])
arr +=10
print("updated array value is:",arr)

import numpy as np
A = np.array([1,2,3,4,5])
B = np.array([6,7,8,9,10])
print(np.add(A,B))

import numpy as np
Arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(sum(arr))

import numpy as np

Arr = np.array([5, 8, 2, 9, 2, 0, 1, 6, 4, 8])

print(np.sort(Arr))

import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,])
print(arr.shape)
print(arr.size)
print(arr.ndim)
print(arr.itemsize)

import numpy as np

arr = np.array([[1, 2, 3, 4],[5, 6, 7, 8]])
print(arr.shape)
print(arr.ndim)
print(arr[0, 1])
print(arr[1, 1])
print(arr[:, 1])

import numpy as np

arr = np.array([1, 2, 3, 4,5, 6, 7, 8,9,10,11,12,13,14,15])
print("original Array",arr)
new = arr.reshape(3,5)
print(new)

